apiVersion: v1
kind: Pod
metadata:
  name: downward-env
spec:
  containers:
  - name: flask-app
    image: YOUR_DOCKER_USERNAME/downward-api:latest
    ports:
    - containerPort: 5000
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
